project:
  type: website
  output-dir: docs

website:
  title: "Quarto Website hosted on GitHub Pages"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    #theme: cosmo
    theme: minty
    css: styles.css
    toc: true

editor: visual

execute:
  echo: true
  warning: false
  message: false

